### ISSUE TITLE
[U.O.S-POS] 포스기 메인페이지 구현

### ISSUE THREAD

**Issue by HyunseungYu** [UOF2021/U.O.F-POS#7]
# 제목
> 포스기 메인페이지 구현
# 목적
> 포스기 앱 실행시 보이는 메인페이지 레이아웃 구성
# 구현기능
1. QR코드 보기 버튼
2. 주문내역 레이아웃
3. 그 외 추후에 추가

**Comment by bapmukza9** [comment]
기능 추가할수록 세부 설명 달아주면 될 듯 합니다.

**Comment by HyunseungYu** [comment]
# 구현기능 추가
메뉴데이터 관리

**Comment by HyunseungYu** [comment]
음식점, 영화관, 피시방 구현 완료

**Comment by HyunseungYu** [comment]
# 메인화면
![메인화면](https://user-images.githubusercontent.com/15906109/132522979-57ad4d7c-61fd-4986-b0db-b9d678281ee9.png)

QR코드 관리 화면
===
![QR코드](https://user-images.githubusercontent.com/15906109/132523046-93ebc950-8589-49ee-8707-0210de815b78.png)

메뉴 관리 화면
=
![메뉴관리](https://user-images.githubusercontent.com/15906109/132523079-2208755c-a42b-4e6d-97a8-0e644854663b.png)

메뉴 추가 화면
=
![메뉴추가](https://user-images.githubusercontent.com/15906109/132523126-60641b9f-a5d0-4cce-b21c-fcccdf136026.png)

**Comment by HyunseungYu** [comment]
# 영화관 화면
![영화관](https://user-images.githubusercontent.com/15906109/132524608-d7d28235-3f1b-4edb-92d4-7d49f1e50a6a.png)
